name: Frontend CI

on:
  push:
    branches: [ main, develop_front ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    defaults:
      run:
        working-directory: ./frontend 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      # Сканирование уязвимостей зависимостей (SCA)
      - name: Run Trivy for frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: 0
          severity: 'CRITICAL,HIGH'

      # Сканирование кода (SAST)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "true"
          sarifFile: "semgrep.sarif"
          config: "auto"

      # Загрузка отчетов
      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
          category: trivy-frontend

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
          category: semgrep-frontend

      # Билд проекта для проверки работоспособности
      - name: Build project
        run: pnpm run build
